/**
 * API Types Barrel Export
 */

// Common types
export type {
  SuccessResponse,
  ErrorDetail,
  ErrorResponse,
  ApiResponse,
  PaginationMeta,
  PaginatedResponse,
  PaginationQuery,
  MessageData,
  MessageResponse,
  ValidationErrorField,
  HealthCheckResponse,
} from './common.types';

// Auth types
export type {
  UserRole,
  UserStatus,
  DeviceType,
  AuthProvider,
  UserProfile as AuthUserProfile,
  SafeUser,
  AuthUser,
  TokenPair,
  TokenPayload,
  LoginRequest,
  RegisterRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  ChangePasswordRequest,
  VerifyEmailRequest,
  RequestEmailChangeRequest,
  ConfirmEmailChangeRequest,
  RefreshTokenRequest,
  MfaVerifyLoginRequest,
  MfaVerifySetupRequest,
  MfaDisableRequest,
  LoginResponseData,
  RegisterResponseData,
  EmailChangeData,
  PasswordStrengthData,
  LoginResponse,
  RegisterResponse,
  CurrentUserResponse,
  RefreshTokenResponse,
  EmailChangeResponse,
  PasswordStrengthResponse,
  UserSession,
  SessionsResponse,
  MfaSetupData,
  MfaStatusData,
  MfaSetupResponse,
  MfaStatusResponse,
  MfaBackupCodesResponse,
  OAuthAccount,
  OAuthProviderInfo,
  OAuthProvidersResponse,
  LinkedAccountsResponse,
  OAuthInitResponse,
} from './auth.types';

export { toAuthUser, isActiveUser, needsVerification } from './auth.types';

// User types
export type {
  DataRegion,
  EmailDigestFrequency,
  ContentRating as UserContentRating,
  UserProfile,
  UpdateProfileRequest,
  UserPreferences,
  UpdatePreferencesRequest,
  UserSecurityInfo,
  LoginHistoryEntry,
  UpdateSecurityRequest,
  ReaderProfile,
  AuthorAccountSummary,
  FullUser,
  UpdateUserRequest,
  PublicUserProfile,
  AdminUserSummary,
  StatusHistoryEntry,
  AdminUserSecurity,
  AdminUserDetail,
  AdminUserQuery,
  AdminUpdateUserRequest,
  AdminUpdateStatusRequest,
  AdminUpdateRoleRequest,
  ImpersonationData,
  GetMeResponse,
  UpdateUserResponse,
  UpdateProfileResponse,
  AvatarUploadResponse,
  GetPreferencesResponse,
  UpdatePreferencesResponse,
  GetSecurityResponse,
  UpdateSecurityResponse,
  LoginHistoryResponse,
  GetPublicUserResponse,
  AdminUserListResponse,
  GetAdminUserResponse,
  ImpersonateResponse,
} from './user.types';

// Author types
export type {
  PlatformTier,
  PlatformSubscriptionStatus,
  BillingCycle,
  AuthorAccount,
  PlatformSubscription,
  AuthorStats,
  AuthorActivity,
  AuthorDashboard,
  PlatformPlanLimits,
  PlatformPlan,
  RegisterAuthorRequest,
  UpdateAuthorAccountRequest,
  SubscribePlatformRequest,
  ChangePlatformPlanRequest,
  AuthorAccountResponse,
  AuthorDashboardResponse,
  AuthorStatsResponse,
  PlatformSubscriptionResponse,
  PlatformPlansResponse,
} from './author.types';

// Site types
export type {
  SiteStatus,
  ContentRating,
  CommentModerationMode,
  CollaboratorRole,
  Site,
  SiteSummary,
  SiteStats,
  SiteActivity,
  SiteOverview,
  SiteGeneralSettings,
  SiteBrandingSettings,
  SiteThemeSettings,
  SiteSeoSettings,
  SiteAnalyticsSettings,
  SiteCommentsSettings,
  SiteSettings,
  DnsRecord,
  SiteDomain,
  Page,
  PageSummary,
  Collaborator,
  CollaboratorInvite,
  CollaboratorSite,
  Theme,
  ThemeSummary,
  CreateSiteRequest,
  UpdateSiteRequest,
  UpdateSiteGeneralRequest,
  UpdateSiteBrandingRequest,
  UpdateSiteThemeRequest,
  UpdateSiteSeoRequest,
  UpdateSiteAnalyticsRequest,
  UpdateSiteCommentsRequest,
  AddDomainRequest,
  CreatePageRequest,
  UpdatePageRequest,
  ReorderPagesRequest,
  InviteCollaboratorRequest,
  UpdateCollaboratorRequest,
  SiteResponse,
  SitesListResponse,
  SiteStatsResponse,
  SiteOverviewResponse,
  SiteSettingsResponse,
  SiteGeneralSettingsResponse,
  SiteBrandingSettingsResponse,
  SiteThemeSettingsResponse,
  SiteSeoSettingsResponse,
  SiteAnalyticsSettingsResponse,
  SiteCommentsSettingsResponse,
  SiteDomainResponse,
  PagesListResponse,
  PageResponse,
  CollaboratorsListResponse,
  CollaboratorResponse,
  CollaboratorInviteResponse,
  CollaboratorSitesResponse,
  ThemesListResponse,
  ThemeResponse,
} from './site.types';

// Public site types
export type {
  PublicNavPage,
  PublicSite,
  PublicPage,
  PublicSiteResponse,
  PublicPageResponse,
} from './public-site.types';